Initial implementation of task 1
IAmFunkyFrog/high-performance-graph-analysis-course pull request #1
Opened 2023-03-12 16:45 UTC by IAmFunkyFrog

# Задача 1. Реализация обхода в ширину (BFS – LEVELS)

- [X] Используя pygraphblas реализовать функцию обхода ориентированного графа в ширину из заданной вершины. При этом организовать все вычисления в виде операций над векторами и матрицами.
  - [X] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [X] Функция возвращает массив, где для каждой вершины указано, на каком шаге она достижима. Стартовая вершина достижима на нулевом шаге, если вершина не достижима, то значение соответствующей ячейки равно -1.
- [X] Добавить необходимые тесты.
- [X] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
    - Проверить, что тесты запускаются только на linux.

2023-03-14 10:08 UTC, rustam-azimov requested changes

2023-03-14 10:08 UTC, rustam-azimov commented on project/bfs.py
> +    result = [-1 for i in range(len(graph.nodes))]
Используйте конструктор разреженного vector из pygraphblas. Причем если -1 заполнять после цикла в самом конце, то можно использовать result как маску при операциях.

2023-03-14 10:08 UTC, rustam-azimov commented on project/bfs.py
> +    for node in graph.nodes:
Лучше чтобы функция принимала Matrix. А чтение из файла и преобразование из Graph отдельными функциями.

2023-03-14 10:08 UTC, rustam-azimov commented on project/bfs.py
> +    while True:
Останавливаемся когда front пуст

2023-03-15 08:15 UTC, IAmFunkyFrog commented on project/bfs.py
> +    result = [-1 for i in range(len(graph.nodes))]
Исправлено

2023-03-15 08:16 UTC, IAmFunkyFrog commented on project/bfs.py
> +    for node in graph.nodes:
Сделал отдельную функцию для матриц

2023-03-15 08:16 UTC, IAmFunkyFrog commented on project/bfs.py
> +    while True:
Исправлено

2023-03-18 07:03 UTC, rustam-azimov approved these changes
5 баллов

2023-03-19 09:34 UTC, merged